// ---------------------------------------------------------------------------
// INTENT_PATTERNS — Natural-language intent keyword map
//
// Maps natural-language intent keywords to slash commands. Used to detect
// what the user wants to do from their message content (e.g., "implement
// this feature" → /build). Each command has an array of trigger phrases
// in both English and Spanish.
// ---------------------------------------------------------------------------

/**
 * Maps natural-language intent keywords to slash commands.
 *
 * Used to detect what the user wants to do from their message content
 * (e.g., "implement this feature" → /build). Each command has an array
 * of trigger phrases in both English and Spanish.
 */
export const INTENT_PATTERNS: Readonly<Record<string, readonly string[]>> = {
	"/spec": [
		"nueva feature",
		"requisito",
		"idea",
		"necesito",
		"quiero crear",
		"new feature",
		"requirement",
		"spec",
		"especificacion",
		"especifica",
		"create",
		"define",
		"write spec",
		"specification",
		"what should",
		"proposal",
		"need a feature",
	],
	"/design": [
		"design",
		"diseña",
		"diseñar",
		"ui",
		"ux",
		"interface",
		"interfaz",
		"mockup",
		"wireframe",
		"layout",
		"component design",
		"design system",
		"user experience",
		"user interface",
		"visual",
		"frontend design",
	],
	"/evolve": [
		"evolucion",
		"evolve",
		"evolucionar",
		"proyecto existente",
		"documentacion viva",
		"living documentation",
		"actualizar docs",
		"modificar spec",
		"nuevo requisito",
		"cambio de requisitos",
		"refinar specs",
		"resolver issue",
		"mantenimiento evolutivo",
		"cliente cambio",
		"client change",
		"nueva funcionalidad",
		"cambiar arquitectura",
		"update documentation",
	],
	"/plan": [
		"planifica",
		"divide",
		"tasks",
		"plan",
		"divide en tareas",
		"divide en",
		"desglosa",
		"breakdown",
		"task breakdown",
		"planning",
		"organize",
		"steps",
		"milestones",
		"task list",
		"todos",
		"to-do",
		"story points",
		"estimate",
	],
	"/build": [
		"implementa",
		"codifica",
		"construye",
		"implement",
		"build",
		"code",
		"escribe el codigo",
		"escribe codigo",
		"write code",
		"create file",
		"add functionality",
		"make",
		"generate",
		"develop",
		"produce",
		"set up",
		"scaffold",
		"boilerplate",
		"create function",
		"create class",
		"create module",
		"create component",
	],
	"/test": [
		"test",
		"prueba",
		"pruebas",
		"testing",
		"unit test",
		"integration test",
		"e2e",
		"specs",
		"coverage",
		"assert",
		"mock",
		"stub",
		"tdd",
		"red-green",
	],
	"/review": [
		"revisa",
		"review",
		"codigo",
		"code review",
		"revisar codigo",
		"code quality",
		"audit",
		"inspect",
		"check code",
		"verify code",
		"static analysis",
		"lint",
		"clean code",
		"best practices",
	],
	"/ship": [
		"ship",
		"deploy",
		"lanza",
		"lanzamiento",
		"deployment",
		"publicar",
		"release",
		"publish",
		"launch",
		"go live",
		"rollout",
		"staging",
		"production",
		"ci/cd",
		"pipeline",
		"deliver",
	],
	"/code-simplify": [
		"simplifica",
		"refactor",
		"limpia",
		"simplify",
		"simplificar",
		"simplify code",
		"clean up",
		"refactor code",
		"improve code",
		"technical debt",
		"complex",
		"duplicate",
		"extract method",
		"reduce complexity",
		"make it simpler",
		"cleanup",
	],
	"/webperf": [
		"performance",
		"rendimiento",
		"core web vitals",
		"lighthouse",
		"web performance",
		"cargar",
		"lcp",
		"inp",
		"cls",
		"performance audit",
		"speed",
		"velocidad",
		"optimizar pagina",
		"page speed",
		"carga de pagina",
		"optimizar rendimiento",
	],
	"/diagnosis": [
		"diagnostico",
		"diagnosis",
		"diagnosticar",
		"analyze issue",
		"analizar problema",
		"investigar",
		"bug report",
		"issue analysis",
		"root cause",
		"causa raiz",
		"por que falla",
		"why is it failing",
		"revisar issue",
		"check issue",
		"troubleshoot",
		"solucionar",
	],
	"/docs-update": [
		"actualizar docs",
		"update docs",
		"update documentation",
		"sync docs",
		"sincronizar documentacion",
		"docs outdated",
		"migrar docs",
		"migrate docs",
		"actualizar documentacion",
		"sync documentation",
		"documentacion desactualizada",
		"regenerar docs",
		"regenerate docs",
		"docs update",
	],
	"/help": [
		// FEV-14 — onboarding command
		"help",
		"ayuda",
		"como uso",
		"how to use",
		"what is",
		"que es",
		"show commands",
		"list commands",
		"menu",
		"onboarding",
		"getting started",
		"como empezar",
		"donde empiezo",
		"documentation",
		"docs",
		"manual",
	],
} as const;
