/**
 * Integration tests for npm packaging.
 *
 * These tests validate that the published npm tarball contains the expected
 * files, excludes files that should be generated post-installation
 * (symlinks, .gitignore), and works correctly when installed.
 *
 * Tests can be skipped with SKIP_NETWORK_TESTS=1.
 */

import { afterAll, beforeAll, describe, expect, it } from "bun:test";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import {
	cleanupTempDir,
	extractTarball,
	listTarballContents,
	packTarball,
	skipPackagingTests,
} from "./packaging-helpers";

// ---------------------------------------------------------------------------
// Test-wide setup
// ---------------------------------------------------------------------------

const describePack = skipPackagingTests() ? describe.skip : describe;
const itPack = skipPackagingTests() ? it.skip : it;

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describePack("npm package — tarball structure", () => {
	let tarballPath: string;

	beforeAll(async () => {
		tarballPath = await packTarball();
	});

	afterAll(async () => {
		if (tarballPath) {
			await cleanupTempDir(path.dirname(tarballPath));
		}
	});

	// -----------------------------------------------------------------------
	// Test A: Expected files present
	// -----------------------------------------------------------------------

	itPack("includes required template files (Test A)", async () => {
		const files = await listTarballContents(tarballPath);
		const allPaths = files.join("\n");

		// Core files
		expect(allPaths).toContain("package/package.json");
		expect(allPaths).toContain("package/src/cli/main.ts");

		// Template obligatorio core files
		expect(allPaths).toContain("package/template/obligatorio/core/opencode.json");
		expect(allPaths).toContain("package/template/obligatorio/packs/main/huitzilopochtli.md");
		expect(allPaths).toContain("package/template/obligatorio/core/commands/build.md");

		// Template estandar files
		expect(allPaths).toContain("package/template/estandar/README.md");
		expect(allPaths).toContain("package/template/estandar/AGENTS.md");
		expect(allPaths).toContain("package/template/estandar/CONTRIBUTING.md");

		// Template estandar — gitignore (renamed to avoid npm exclusion)
		expect(allPaths).toContain("package/template/estandar/gitignore");
	});

	// -----------------------------------------------------------------------
	// Test D: Symlinks are NOT in the tarball
	// -----------------------------------------------------------------------

	itPack("excludes symlinks — they are generated post-install (Test D)", async () => {
		const files = await listTarballContents(tarballPath);
		const allPaths = files.join("\n");

		// Symlinks that should NOT be present (they're generated by BunSymlinkCreator)
		expect(allPaths).not.toContain("package/template/obligatorio/core/.opencode/agents");
		expect(allPaths).not.toContain("package/template/obligatorio/core/.opencode/commands");
		expect(allPaths).not.toContain("package/template/obligatorio/core/.opencode/skills");
	});

	// -----------------------------------------------------------------------
	// Test E: .gitignore is NOT in the tarball (npm excludes it)
	// -----------------------------------------------------------------------

	itPack("excludes .gitignore files — npm strips them (Test E)", async () => {
		const files = await listTarballContents(tarballPath);
		const allPaths = files.join("\n");

		// .gitignore files should NOT be in the tarball (npm excludes all .gitignore)
		expect(allPaths).not.toContain(".gitignore");

		// The renamed version (gitignore without dot) SHOULD be present
		expect(allPaths).toContain("package/template/estandar/gitignore");
	});
});

// ---------------------------------------------------------------------------
// Extracted package tests (more expensive — require tarball extraction)
// ---------------------------------------------------------------------------

describePack("npm package — extracted installation", () => {
	let tarballPath: string;
	let packageDir: string;

	beforeAll(async () => {
		tarballPath = await packTarball();
		packageDir = await extractTarball(tarballPath);
	});

	afterAll(async () => {
		if (tarballPath) await cleanupTempDir(path.dirname(tarballPath));
		if (packageDir) await cleanupTempDir(path.dirname(packageDir));
	});

	// -----------------------------------------------------------------------
	// Test B: Binary --version works from installed package
	// -----------------------------------------------------------------------

	itPack(
		"binary --version works from extracted package (Test B)",
		async () => {
			// Install dependencies in the package dir (needed for @clack/prompts etc.)
			const installProc = Bun.spawnSync(["bun", "install"], {
				cwd: packageDir,
			});
			expect(installProc.exitCode).toBe(0);

			// Run --version
			const versionProc = Bun.spawnSync(["bun", "run", "src/cli/main.ts", "--version"], {
				cwd: packageDir,
			});
			expect(versionProc.exitCode).toBe(0);
			expect(versionProc.stdout.toString()).toContain("Códice");
		},
		{ timeout: 30000 },
	);

	// -----------------------------------------------------------------------
	// Test C: Clean install from extracted package
	// -----------------------------------------------------------------------

	itPack(
		"clean install works from extracted package (Test C)",
		async () => {
			// Must avoid system directories — macOS os.tmpdir() is /var/folders/
			// which is blocked by SYSTEM_DIRS in validateDestPath (parse-args.ts:66).
			// Use process.cwd() which is the CI workspace (always a valid project dir).
			const installDir = await fs.mkdtemp(path.join(process.cwd(), ".codice-clean-test-"));

			try {
				const proc = Bun.spawnSync(
					["bun", "run", "src/cli/main.ts", "--clean", "--force", "--dest", installDir],
					{
						cwd: packageDir,
					},
				);

				expect(proc.exitCode).toBe(0);

				// Verify key template files were installed
				const installedFiles = await fs.readdir(installDir);

				// .opencode directory should exist (obligatorio)
				expect(installedFiles).toContain(".opencode");

				// .gitignore should exist (generated post-install)
				const gitignorePath = path.join(installDir, ".gitignore");
				const gitignoreExists = await fs
					.access(gitignorePath)
					.then(() => true)
					.catch(() => false);
				expect(gitignoreExists).toBe(true);
			} finally {
				await fs.rm(installDir, { recursive: true, force: true });
			}
		},
		{ timeout: 30000 },
	);
});
