/**
 * output-format.ts — Shared output formatting for analyze-references.ts
 *
 * Extracted from analyze-references.ts to keep files under the project's
 * 200-line limit (CODE_STYLE.md) while maintaining readability.
 */

import { relative } from "node:path";
import { writeFileSync } from "node:fs";
import type { ReferenceMapping } from "./analyze-references";

// ── Stats ──────────────────────────────────────────────────────────────────────

export interface Stats {
	readonly high: number;
	readonly med: number;
	readonly low: number;
	readonly uniqueSkills: number;
	readonly bySkill: Map<string, number>;
}

/**
 * Compute aggregate statistics from a set of reference mappings in a single pass.
 */
export function computeStats(mappings: ReferenceMapping[]): Stats {
	let high = 0;
	let med = 0;
	let low = 0;
	const uniqueSkills = new Set<string>();
	const bySkill = new Map<string, number>();

	for (const m of mappings) {
		if (m.confidence === "HIGH") high++;
		else if (m.confidence === "MEDIUM") med++;
		else low++;

		uniqueSkills.add(m.targetSkill);
		bySkill.set(m.targetSkill, (bySkill.get(m.targetSkill) ?? 0) + 1);
	}

	return { high, med, low, uniqueSkills: uniqueSkills.size, bySkill };
}

// ── Markdown output ────────────────────────────────────────────────────────────

/**
 * Generate the full mapping table markdown document.
 * Writes to the configured output path.
 */
export function generateMarkdown(
	mappings: ReferenceMapping[],
	projectRoot: string,
	outputFile: string,
): void {
	const { high, med, low, bySkill } = computeStats(mappings);

	const mdFiles = mappings.filter((m) => m.filename.endsWith(".md")).length;
	const nonMdFiles = mappings.length - mdFiles;

	const lines: string[] = [
		"# FEV-12 — References-to-Skills Mapping Table",
		"",
		"**Generated by:** `scripts/analyze-references.ts`",
		`**Date:** ${new Date().toISOString().slice(0, 10)}`,
		`**Total files:** ${mappings.length} (${mdFiles} .md + ${nonMdFiles} non-.md)`,
		"",
		"## Confidence Level Distribution",
		"",
		"| Confidence | Count |",
		"|------------|-------|",
		`| HIGH       | ${high} |`,
		`| MEDIUM     | ${med} |`,
		`| LOW        | ${low} |`,
		`| **Total**  | **${mappings.length}** |`,
		"",
		"## Distribution by Skill",
		"",
		"| Skill | References |",
		"|-------|------------|",
	];

	for (const [skill, count] of [...bySkill.entries()].sort()) {
		lines.push(`| ${skill} | ${count} |`);
	}
	lines.push("");

	// Full mapping table
	lines.push("## Full Mapping", "", "| # | File | Target Skill | Confidence | Rationale |", "|---|------|--------------|------------|-----------|");

	let idx = 1;
	for (const m of mappings) {
		const badge = m.confidence === "HIGH" ? "🟢 HIGH" : m.confidence === "MEDIUM" ? "🟡 MEDIUM" : "🔴 LOW";
		lines.push(`| ${idx++} | \`${m.filename}\` | \`${m.targetSkill}\` | ${badge} | ${m.rationale} |`);
	}
	lines.push("");

	// Files needing manual review
	const lowFiles = mappings.filter((m) => m.confidence === "LOW");
	if (lowFiles.length > 0) {
		lines.push(
			"## ⚠️ Files Requiring Manual Review (LOW confidence)",
			"",
			"These files had no direct SKILL.md mentions. They were assigned based on",
			"content/keyword analysis. Review the assignments below:",
			"",
		);
		for (const m of lowFiles) {
			lines.push(`- **\`${m.filename}\`** → \`${m.targetSkill}\` — ${m.rationale}`);
		}
		lines.push("");
	}

	writeFileSync(outputFile, lines.join("\n"), "utf-8");
	console.log(`\n  Output written to: ${relative(projectRoot, outputFile)}`);
}

// ── Console summary ────────────────────────────────────────────────────────────

export function printSummary(mappings: ReferenceMapping[]): void {
	const { high, med, low, uniqueSkills } = computeStats(mappings);

	console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
	console.log("  FEV-12 Reference Analysis Summary");
	console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
	console.log(`  Total files analyzed:  ${mappings.length}`);
	console.log(`  Unique skills target:  ${uniqueSkills}`);
	console.log(`  HIGH confidence:       ${high}  (direct SKILL.md mention)`);
	console.log(`  MEDIUM confidence:     ${med}  (cross-reference resolution)`);
	console.log(`  LOW confidence:        ${low}  (content-based / manual override)`);
	console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");

	for (const m of mappings) {
		const icon = m.confidence === "HIGH" ? "✓" : m.confidence === "MEDIUM" ? "~" : "?";
		console.log(`  ${icon} ${m.filename.padEnd(42)} → ${m.targetSkill}`);
	}
}
